apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgAGoeb3g9dmuOwqSNXbGHo45/jm20uf4lP0MCaNvlepix2cbpJksauLetHRZeOMqj2OI6U5MeIYh5nJpnVNYNB3UNd9QjH4nvr5waGJMX9s7EmMPzYJWfW6t/eIkTAtistmkTbhE1MOyoBQaCPrOFTirCJRSfy+WOgcYV2JcZYMMZr9UVY5T+Xop6vZ+bqDegrDWnx6Q2wfsK96knLb7o2SMwpBMpaEzyzZAWL+7fnNd+U3HIA74xT9C/YuNV1TeN1gwveZjR1NrtAOPtqSlE4TttktS0fkztm5rykpAfAgKMY9Itogtw8JefB2cPVY2Q7MMP7xUPLaHz4fGVBYbJXudBbiYnrfWg7gxZ/lX/xryzQu/nKNjvPetzv1mxeQ/gOriuam2K71VEWJhGb2GodRWFdowujgRG6ItV++ZS3bzfNbAdKY3Rd+qY7tbvU0BklXr6EeEZeO3QZubEFy535l9ZPL3GRYWMcxFfP5y1ehh6FXpgtq5426Og9G9D1+3u9zw/xcsra4GTm0yw2L0mWJUr4byGweiur4oyWJfifqVl/hXEbWKGkGD1EHN4CtdRugFTzqDZASmb0FXs2lVuwyQGsW01UdaXAtS1+jtOb2PIVaH9hZE4fPyjFYcIyuRJyG1ypp58yEIL20X2D26vkOmy1MsCfCJMy5PIjVEEw6Pkr33gUDbT9BDe1WhTDuHmahqWowibHhfKOjWnoJvaCm3HRHt5JCSoN3W7c4gq1+X5SxltTdLAuwHlGA0maqmUZnWi/3NJyblo4Eq/3yKWpdtrQ4/fbRbXW8Wj2/MDKsXy+Lsnj/SnHPLVauJqF+8HidB1ql2PkxvKEFux0CVY8PAiIUlcE=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

