apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgCf3NuGl8rpzvQiqhJp2/QXzA7eIDjNDooTOsrCm0sCG0c2dyq7TKa5hrMq9C4LwEYoZHzsxiBzfxhlRPs5K1/izIb4gbsnIyK7MaO0H4F7hD3FBnsIyANMq8BV4Ou+nylHX/CVyYT+g2+eKmERj09XOebMVyfM/M4CozlJUj5xbbOjK25hWxIsJmj5BaGU86+PVEuA7S4Rc8ejqg4/l6Se41W4sQNNEQGt1ynasrsMLSIgTD8GEtz6zym7tR3ZfWfp48Gg330fZ9ROenLfMg9KGzC7nCpW6uVcNL3uO+M9agx74OCwko2e4YRjvQ6/KMlaktWD1FZn/RYijzrsK1XgE3z1g7qd8w6z/SQYurn/6MOak+Dpx9h4WRowku804OnPpN9cOVuqwSlWla82v7LI6pckXwYa7/S2gDP2RPaK/6+N2RKgYQ1fR3Ujj3Xkl2q5IwkhjKKwJXgDSO6SO3rGRtx7VYmELe3Fd7lvC0WVUYNKYy3hcx/Wl9yFzs1Woe0wxrZD02q5Em2l9CxVfXdlqvNG9+ko706LHrkJ/kjai4uSIvUGcEQZsJwp9R5Utl3bVXG0QqWG9G28ZUKfeJAhPe6tU55+NMNteQlEiLQz9q9wH3vEnQo3mrN/ieQbAcVWPHkigg14tXeUIoNwH4lPtdhlgaVb1iHwUSPsTwYq5bXnLcVb4xP+QPI4s23gw2RZ+0E7GwH/ovKnobsC35BG+QreM+pO4Q99HGOxhRlR6bXqPFR7PCB0Up01QqWP7NXVyl6d1aLfd+aoOAWixQkVrXR91NlBfNclK66rCvFcQct3D+6pjucCZI9Sf/48+zx/HZ+ibvPjWWFr1NyKVk9QPu6ASz4=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

